field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
    inter: [user_id, item_id, rating, timestamp]

NEG_PREFIX: neg_
LABEL_FIELD: label
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id

filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# training settings
epochs: 150
train_batch_size: 2048
learner: adam
learning_rate: 0.001
training_neg_sample_num: 0
eval_step: 1
stopping_step: 30
# evalution settings
eval_setting: TO_LS,full
metrics: ["Recall", "NDCG"]
valid_metric: NDCG@10
eval_batch_size: 256
weight_decay: 0
topk: [5, 10, 20]

log_root: "./log/"
data_path: "./dataset/"

